#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define BUF_SIZE 4096
#define PROC_PERMS (PROCESS_CREATE_THREAD | PROCESS_VM_OPERATION | PROCESS_VM_WRITE | PROCESS_VM_READ)

#endif//CONFIG_H_INCLUDED
